/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'shortDescription' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBookmarkedLessonIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getLessonById' : IDL.Func([IDL.Nat], [IDL.Opt(Lesson)], ['query']),
  'getLessonsByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(Lesson)], ['query']),
  'getUserBookmarks' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBookmark' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchLessons' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'shortDescription' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBookmarkedLessonIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getLessonById' : IDL.Func([IDL.Nat], [IDL.Opt(Lesson)], ['query']),
    'getLessonsByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(Lesson)], ['query']),
    'getUserBookmarks' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBookmark' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchLessons' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };